/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homesecurity;

import java.io.File;
import java.io.IOException;
import java.math.BigInteger;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author adria
 */
public class MainWindow extends javax.swing.JFrame
{
    public String stringReadFromFileEncryption;
    public String stringReadFromFileDecryption;
    public byte[] bytesReadFromFileEncryption;
    public byte[] bytesReadFromFileDecryption;
    public byte[] encryptedBytes;
    public byte[] decryptedBytes;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
    }
    
    private void enableEncryptButtonCheck()
    {
        if (!RSAKeyText.getText().isEmpty() && !NKeyText.getText().isEmpty()
                && !originalFileTextArea.getText().isEmpty())
        {
            encryptButton.setEnabled(true);
        }
        else
        {
            encryptButton.setEnabled(false);
        }
    }
    
    private void enableDecryptButtonCheck()
    {
        if (!RSADecryptKeyTextField.getText().isEmpty() && !NDecryptKeyTextField.getText().isEmpty()
                && !encryptedFilenameDecryptionField.getText().isEmpty())
        {
            decryptButton.setEnabled(true);
        }
        else
        {
            decryptButton.setEnabled(false);
        }
    }
    
    private void copyText(JTextField destination, JTextField source)
    {
        destination.setText(source.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        tabbedPane = new javax.swing.JTabbedPane();
        encryptTab = new javax.swing.JPanel();
        encryptButton = new javax.swing.JButton();
        RSAKeyLabel = new javax.swing.JLabel();
        nLabel = new javax.swing.JLabel();
        RSAKeyText = new javax.swing.JTextField();
        NKeyText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        originalFileTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        encryptedTextArea = new javax.swing.JTextArea();
        originalFilenameField = new javax.swing.JTextField();
        encryptedFilenameField = new javax.swing.JTextField();
        chooseFileButton = new javax.swing.JButton();
        originalFileLabel = new javax.swing.JLabel();
        previewLabel = new javax.swing.JLabel();
        encryptedFileLabel = new javax.swing.JLabel();
        decryptTab = new javax.swing.JPanel();
        decryptionPreviewLabel = new javax.swing.JLabel();
        decryptionEncryptedFilenameLabel = new javax.swing.JLabel();
        encryptedFilenameDecryptionField = new javax.swing.JTextField();
        decryptChooseFileButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        loadedEncryptedFileTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        decryptedFileTextArea = new javax.swing.JTextArea();
        decryptButton = new javax.swing.JButton();
        NDecryptKeyTextField = new javax.swing.JTextField();
        RSADecryptKeyTextField = new javax.swing.JTextField();
        RSADecryptKeyLabel = new javax.swing.JLabel();
        NKeyDecryptKeyLabel = new javax.swing.JLabel();
        decryptedFilenameField = new javax.swing.JTextField();
        decryptionDecryptedFilenameLabel = new javax.swing.JLabel();
        transferTab = new javax.swing.JPanel();
        keyManagementTab = new javax.swing.JPanel();
        generateKeysButton = new javax.swing.JButton();
        generatedPublicKeyTextArea = new javax.swing.JTextField();
        generatedPrivateKeyTextArea = new javax.swing.JTextField();
        generatedNTextArea = new javax.swing.JTextField();
        savePublicKeyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loadKeyButton = new javax.swing.JButton();
        generatedPublicKeyToEncryptionButton = new javax.swing.JButton();
        generatedPublicKeyToDecryptionButton = new javax.swing.JButton();
        savePrivateKeyButton = new javax.swing.JButton();
        generatedPrivateKeyToEncryptionButton = new javax.swing.JButton();
        generatedPrivateKeyToDecryptionButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        loadedKeyTextArea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        loadedNTextArea = new javax.swing.JTextField();
        useLoadedKeyOnEncryptionButton = new javax.swing.JButton();
        useLoadedKeyOnDecryptionButton = new javax.swing.JButton();
        deleteKeyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        encryptButton.setText("Criptografar");
        encryptButton.setEnabled(false);
        encryptButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                encryptButtonActionPerformed(evt);
            }
        });

        RSAKeyLabel.setText("Chave RSA");

        nLabel.setText("N");

        RSAKeyText.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                RSAKeyTextKeyTyped(evt);
            }
        });

        NKeyText.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                NKeyTextKeyTyped(evt);
            }
        });

        originalFileTextArea.setEditable(false);
        originalFileTextArea.setColumns(20);
        originalFileTextArea.setRows(5);
        jScrollPane1.setViewportView(originalFileTextArea);

        encryptedTextArea.setEditable(false);
        encryptedTextArea.setColumns(20);
        encryptedTextArea.setRows(5);
        jScrollPane2.setViewportView(encryptedTextArea);

        originalFilenameField.setEditable(false);

        encryptedFilenameField.setEditable(false);

        chooseFileButton.setText("Escolher arquivo...");
        chooseFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chooseFileButtonActionPerformed(evt);
            }
        });

        originalFileLabel.setText("Arquivo original");

        previewLabel.setText("Pré-visualização");

        encryptedFileLabel.setText("Arquivo criptografado");

        javax.swing.GroupLayout encryptTabLayout = new javax.swing.GroupLayout(encryptTab);
        encryptTab.setLayout(encryptTabLayout);
        encryptTabLayout.setHorizontalGroup(
            encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(encryptTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encryptTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(encryptTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(encryptTabLayout.createSequentialGroup()
                        .addComponent(encryptedFileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(encryptedFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptTabLayout.createSequentialGroup()
                        .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(originalFileLabel)
                            .addComponent(previewLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chooseFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(originalFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptTabLayout.createSequentialGroup()
                        .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(encryptTabLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RSAKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(encryptTabLayout.createSequentialGroup()
                                .addComponent(RSAKeyLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(encryptTabLayout.createSequentialGroup()
                                .addComponent(nLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(NKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(encryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        encryptTabLayout.setVerticalGroup(
            encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptTabLayout.createSequentialGroup()
                .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(encryptTabLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(originalFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseFileButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encryptTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(previewLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(originalFileLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encryptedFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encryptedFileLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(encryptTabLayout.createSequentialGroup()
                        .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RSAKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RSAKeyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(encryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NKeyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nLabel))))
                .addGap(22, 22, 22))
        );

        tabbedPane.addTab("Criptografar", encryptTab);

        decryptionPreviewLabel.setText("Pré-visualização");

        decryptionEncryptedFilenameLabel.setText("Arquivo criptografado");

        encryptedFilenameDecryptionField.setEditable(false);

        decryptChooseFileButton.setText("Escolher arquivo...");
        decryptChooseFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                decryptChooseFileButtonActionPerformed(evt);
            }
        });

        loadedEncryptedFileTextArea.setEditable(false);
        loadedEncryptedFileTextArea.setColumns(20);
        loadedEncryptedFileTextArea.setRows(5);
        jScrollPane3.setViewportView(loadedEncryptedFileTextArea);

        decryptedFileTextArea.setEditable(false);
        decryptedFileTextArea.setColumns(20);
        decryptedFileTextArea.setRows(5);
        jScrollPane4.setViewportView(decryptedFileTextArea);

        decryptButton.setText("Decriptografar");
        decryptButton.setEnabled(false);
        decryptButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                decryptButtonActionPerformed(evt);
            }
        });

        NDecryptKeyTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                NDecryptKeyTextFieldKeyTyped(evt);
            }
        });

        RSADecryptKeyTextField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                RSADecryptKeyTextFieldKeyTyped(evt);
            }
        });

        RSADecryptKeyLabel.setText("Chave RSA");

        NKeyDecryptKeyLabel.setText("N");

        decryptedFilenameField.setEditable(false);

        decryptionDecryptedFilenameLabel.setText("Arquivo decriptografado");

        javax.swing.GroupLayout decryptTabLayout = new javax.swing.GroupLayout(decryptTab);
        decryptTab.setLayout(decryptTabLayout);
        decryptTabLayout.setHorizontalGroup(
            decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decryptTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptTabLayout.createSequentialGroup()
                        .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RSADecryptKeyLabel)
                            .addComponent(NKeyDecryptKeyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NDecryptKeyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addComponent(RSADecryptKeyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(decryptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(decryptTabLayout.createSequentialGroup()
                        .addComponent(decryptionEncryptedFilenameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(decryptChooseFileButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(encryptedFilenameDecryptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(decryptTabLayout.createSequentialGroup()
                        .addComponent(decryptionPreviewLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptTabLayout.createSequentialGroup()
                        .addComponent(decryptionDecryptedFilenameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(decryptedFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        decryptTabLayout.setVerticalGroup(
            decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, decryptTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(decryptionPreviewLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decryptionEncryptedFilenameLabel)
                    .addComponent(encryptedFilenameDecryptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptChooseFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decryptedFilenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptionDecryptedFilenameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(decryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(decryptTabLayout.createSequentialGroup()
                        .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RSADecryptKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RSADecryptKeyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(decryptTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NDecryptKeyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NKeyDecryptKeyLabel))))
                .addContainerGap())
        );

        tabbedPane.addTab("Decriptografar", decryptTab);

        javax.swing.GroupLayout transferTabLayout = new javax.swing.GroupLayout(transferTab);
        transferTab.setLayout(transferTabLayout);
        transferTabLayout.setHorizontalGroup(
            transferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        transferTabLayout.setVerticalGroup(
            transferTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Transmitir", transferTab);

        generateKeysButton.setText("Gerar par de chaves");
        generateKeysButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generateKeysButtonActionPerformed(evt);
            }
        });

        generatedPublicKeyTextArea.setMaximumSize(new java.awt.Dimension(6, 20));

        generatedPrivateKeyTextArea.setMaximumSize(new java.awt.Dimension(6, 20));

        generatedNTextArea.setMaximumSize(new java.awt.Dimension(607, 20));

        savePublicKeyButton.setText("Salvar");
        savePublicKeyButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                savePublicKeyButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Chave pública:");

        jLabel4.setText("Chave privada:");

        jLabel5.setText("N:");

        loadKeyButton.setText("Carregar chave");
        loadKeyButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loadKeyButtonActionPerformed(evt);
            }
        });

        generatedPublicKeyToEncryptionButton.setText("Usar na criptografia");
        generatedPublicKeyToEncryptionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generatedPublicKeyToEncryptionButtonActionPerformed(evt);
            }
        });

        generatedPublicKeyToDecryptionButton.setText("Usar na decriptografia");
        generatedPublicKeyToDecryptionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generatedPublicKeyToDecryptionButtonActionPerformed(evt);
            }
        });

        savePrivateKeyButton.setText("Salvar");

        generatedPrivateKeyToEncryptionButton.setText("Usar na criptografia");
        generatedPrivateKeyToEncryptionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generatedPrivateKeyToEncryptionButtonActionPerformed(evt);
            }
        });

        generatedPrivateKeyToDecryptionButton.setText("Usar na decriptografia");
        generatedPrivateKeyToDecryptionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                generatedPrivateKeyToDecryptionButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Chave:");

        jLabel7.setText("N:");

        useLoadedKeyOnEncryptionButton.setText("Usar na criptografia");
        useLoadedKeyOnEncryptionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                useLoadedKeyOnEncryptionButtonActionPerformed(evt);
            }
        });

        useLoadedKeyOnDecryptionButton.setText("Usar na decriptografia");
        useLoadedKeyOnDecryptionButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                useLoadedKeyOnDecryptionButtonActionPerformed(evt);
            }
        });

        deleteKeyButton.setText("Apagar");

        javax.swing.GroupLayout keyManagementTabLayout = new javax.swing.GroupLayout(keyManagementTab);
        keyManagementTab.setLayout(keyManagementTabLayout);
        keyManagementTabLayout.setHorizontalGroup(
            keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyManagementTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(keyManagementTabLayout.createSequentialGroup()
                        .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generateKeysButton)
                            .addGroup(keyManagementTabLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(generatedPrivateKeyTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(keyManagementTabLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(generatedPublicKeyTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(keyManagementTabLayout.createSequentialGroup()
                                .addComponent(savePublicKeyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatedPublicKeyToEncryptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatedPublicKeyToDecryptionButton))
                            .addGroup(keyManagementTabLayout.createSequentialGroup()
                                .addComponent(savePrivateKeyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatedPrivateKeyToEncryptionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatedPrivateKeyToDecryptionButton))))
                    .addComponent(loadKeyButton)
                    .addGroup(keyManagementTabLayout.createSequentialGroup()
                        .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyManagementTabLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteKeyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(useLoadedKeyOnEncryptionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(useLoadedKeyOnDecryptionButton))
                            .addComponent(loadedKeyTextArea)
                            .addComponent(loadedNTextArea)))
                    .addGroup(keyManagementTabLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(generatedNTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        keyManagementTabLayout.setVerticalGroup(
            keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyManagementTabLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(loadKeyButton)
                .addGap(18, 18, 18)
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(loadedKeyTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loadedNTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(useLoadedKeyOnEncryptionButton)
                    .addComponent(useLoadedKeyOnDecryptionButton)
                    .addComponent(deleteKeyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(generateKeysButton)
                .addGap(28, 28, 28)
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePublicKeyButton)
                    .addComponent(generatedPublicKeyToEncryptionButton)
                    .addComponent(generatedPublicKeyToDecryptionButton)
                    .addComponent(generatedPublicKeyTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatedPrivateKeyTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(savePrivateKeyButton)
                    .addComponent(generatedPrivateKeyToEncryptionButton)
                    .addComponent(generatedPrivateKeyToDecryptionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(keyManagementTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generatedNTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(178, 178, 178))
        );

        tabbedPane.addTab("Chaves", keyManagementTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadKeyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loadKeyButtonActionPerformed
    {//GEN-HEADEREND:event_loadKeyButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Carregar chave");
        fileChooser.setFileFilter(new PublicKeyFileFilter());
        fileChooser.setFileFilter(new PrivateKeyFileFilter());
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.CANCEL_OPTION)
        {
            return;
        }

        File chosenFile = fileChooser.getSelectedFile();

        if(chosenFile == null || chosenFile.getName().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nome inválido", "Nome inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String path = chosenFile.getAbsolutePath();
        
        if (!chosenFile.exists()) return;

        try 
        {
            Scanner scanner = new Scanner(chosenFile);
            
            BigInteger loadedKey = new BigInteger(scanner.nextLine());
            BigInteger loadedN = new BigInteger(scanner.nextLine());
            
            System.out.println("Loaded keys:");
            System.out.println("KEY = " + loadedKey.toString());
            System.out.println("N = " + loadedN.toString());
            
            /*bytesReadFromFileEncryption = TextReader.readFile(path);
            stringReadFromFileEncryption = new String(bytesReadFromFileEncryption);
            
            System.out.println("String read from file: ");
            System.out.println(stringReadFromFileEncryption);
            
            originalFileTextArea.setText(stringReadFromFileEncryption);
            originalFilenameField.setText(path);
            
            enableEncryptButtonCheck();*/
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loadKeyButtonActionPerformed

    private void savePublicKeyButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_savePublicKeyButtonActionPerformed
    {//GEN-HEADEREND:event_savePublicKeyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePublicKeyButtonActionPerformed

    private void generateKeysButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generateKeysButtonActionPerformed
    {//GEN-HEADEREND:event_generateKeysButtonActionPerformed
        final int PUBLIC = 0;
        final int PRIVATE = 1;
        
        RSAKey keyPair[] = KeyFactory.generatePair();
        
        generatedPublicKeyTextArea.setText(keyPair[PUBLIC].key.toString());
        generatedPrivateKeyTextArea.setText(keyPair[PRIVATE].key.toString());
        generatedNTextArea.setText(keyPair[PRIVATE].n.toString());
    }//GEN-LAST:event_generateKeysButtonActionPerformed

    private void useLoadedKeyOnEncryptionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_useLoadedKeyOnEncryptionButtonActionPerformed
    {//GEN-HEADEREND:event_useLoadedKeyOnEncryptionButtonActionPerformed
        copyText(RSAKeyText, loadedKeyTextArea);
        copyText(NKeyText, loadedNTextArea);
        enableEncryptButtonCheck();
    }//GEN-LAST:event_useLoadedKeyOnEncryptionButtonActionPerformed

    private void generatedPublicKeyToEncryptionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generatedPublicKeyToEncryptionButtonActionPerformed
    {//GEN-HEADEREND:event_generatedPublicKeyToEncryptionButtonActionPerformed
        copyText(RSAKeyText, generatedPublicKeyTextArea);
        copyText(NKeyText, generatedNTextArea);
        enableEncryptButtonCheck();
    }//GEN-LAST:event_generatedPublicKeyToEncryptionButtonActionPerformed

    private void generatedPrivateKeyToEncryptionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generatedPrivateKeyToEncryptionButtonActionPerformed
    {//GEN-HEADEREND:event_generatedPrivateKeyToEncryptionButtonActionPerformed
        copyText(RSAKeyText, generatedPrivateKeyTextArea);
        copyText(NKeyText, generatedNTextArea);
        enableEncryptButtonCheck();
    }//GEN-LAST:event_generatedPrivateKeyToEncryptionButtonActionPerformed

    private void encryptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_encryptButtonActionPerformed
    {//GEN-HEADEREND:event_encryptButtonActionPerformed
        String inputKey;
        String inputN;
        BigInteger bigIntegerKey;
        BigInteger bigIntegerN;
        
        inputKey = RSAKeyText.getText();
        //System.out.println("Input key is: " + inputKey);
        
        inputN = NKeyText.getText();
        //System.out.println("Input n is: " + inputN);
        
        if (inputKey.isEmpty() || inputN.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Especifique uma chave RSA e o parâmetro N", "Campos não preenchidos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        /* RSA Encryption section */
        
        try { bigIntegerKey = new BigInteger(inputKey); }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Chave RSA com formato incorreto (não é um número)", "Parâmetro incorreto", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
        try { bigIntegerN = new BigInteger(inputN); }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Parâmetro N com formato incorreto (não é um número)", "Parâmetro incorreto", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        RSAKey key = new RSAKey(bigIntegerKey, bigIntegerN);
        Encrypter encrypter = new Encrypter(key);
        
        encryptedBytes = encrypter.encrypt(bytesReadFromFileEncryption);
        
        System.out.println("Encrypted bytes are ready to rock");
        /* End of RSA encryption section */
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Salvar arquivo encriptado como");
        fileChooser.setFileFilter(new TextFileFilter());
        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.CANCEL_OPTION)
        {
            return;
        }

        File chosenFile = fileChooser.getSelectedFile();

        if(chosenFile.getName().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nome inválido", "Nome inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String pathToWrite = chosenFile.getAbsolutePath() + ".txt";
        System.out.println("Chosen file to write: " + pathToWrite);
        
        try 
        {
            TextWriter.writeOnFile(pathToWrite, encryptedBytes);
            
            encryptedFilenameField.setText(pathToWrite);
            encryptedTextArea.setText(new String(encryptedBytes));
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Erro", "Não foi possível criar o arquivo", JOptionPane.ERROR_MESSAGE);
        }
        
        JOptionPane.showMessageDialog(this, "Encriptação realizada com sucesso!", "Mensagem encriptada", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_encryptButtonActionPerformed

    private void chooseFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chooseFileButtonActionPerformed
    {//GEN-HEADEREND:event_chooseFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Abrir arquivo");
        fileChooser.setFileFilter(new TextFileFilter());
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.CANCEL_OPTION)
        {
            return;
        }

        File chosenFile = fileChooser.getSelectedFile();

        if(chosenFile == null || chosenFile.getName().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nome inválido", "Nome inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String path = chosenFile.getAbsolutePath();
        System.out.println("File path: " + path);
        
        if (!chosenFile.exists()) return;

        try 
        {
            bytesReadFromFileEncryption = TextReader.readFile(path);
            stringReadFromFileEncryption = new String(bytesReadFromFileEncryption);
            
            System.out.println("String read from file: ");
            System.out.println(stringReadFromFileEncryption);
            
            originalFileTextArea.setText(stringReadFromFileEncryption);
            originalFilenameField.setText(path);
            
            enableEncryptButtonCheck();
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chooseFileButtonActionPerformed

    private void RSAKeyTextKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_RSAKeyTextKeyTyped
    {//GEN-HEADEREND:event_RSAKeyTextKeyTyped
        enableEncryptButtonCheck();
    }//GEN-LAST:event_RSAKeyTextKeyTyped

    private void NKeyTextKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NKeyTextKeyTyped
    {//GEN-HEADEREND:event_NKeyTextKeyTyped
        enableEncryptButtonCheck();
    }//GEN-LAST:event_NKeyTextKeyTyped

    private void RSADecryptKeyTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_RSADecryptKeyTextFieldKeyTyped
    {//GEN-HEADEREND:event_RSADecryptKeyTextFieldKeyTyped
        enableDecryptButtonCheck();
    }//GEN-LAST:event_RSADecryptKeyTextFieldKeyTyped

    private void NDecryptKeyTextFieldKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NDecryptKeyTextFieldKeyTyped
    {//GEN-HEADEREND:event_NDecryptKeyTextFieldKeyTyped
        enableDecryptButtonCheck();
    }//GEN-LAST:event_NDecryptKeyTextFieldKeyTyped

    private void decryptChooseFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_decryptChooseFileButtonActionPerformed
    {//GEN-HEADEREND:event_decryptChooseFileButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Abrir arquivo criptografado");
        fileChooser.setFileFilter(new TextFileFilter());
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.CANCEL_OPTION)
        {
            return;
        }

        File chosenFile = fileChooser.getSelectedFile();

        if(chosenFile == null || chosenFile.getName().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nome inválido", "Nome inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String path = chosenFile.getAbsolutePath();
        System.out.println("File path: " + path);
        
        if (!chosenFile.exists()) return;

        try 
        {
            bytesReadFromFileDecryption = TextReader.readFile(path);
            stringReadFromFileDecryption = new String(bytesReadFromFileDecryption);
            
            System.out.println("String read from file: ");
            System.out.println(stringReadFromFileDecryption);
            
            loadedEncryptedFileTextArea.setText(stringReadFromFileDecryption);
            encryptedFilenameDecryptionField.setText(path);
            
            enableDecryptButtonCheck();
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Não foi possível abrir o arquivo", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_decryptChooseFileButtonActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_decryptButtonActionPerformed
    {//GEN-HEADEREND:event_decryptButtonActionPerformed
        String inputKey;
        String inputN;
        BigInteger bigIntegerKey;
        BigInteger bigIntegerN;
        
        inputKey = RSADecryptKeyTextField.getText();
        //System.out.println("Input key is: " + inputKey);
        
        inputN = NDecryptKeyTextField.getText();
        //System.out.println("Input n is: " + inputN);
        
        if (inputKey.isEmpty() || inputN.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Especifique uma chave RSA e o parâmetro N", "Campos não preenchidos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        /* RSA Encryption section */
        
        try { bigIntegerKey = new BigInteger(inputKey); }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Chave RSA com formato incorreto (não é um número)", "Parâmetro incorreto", JOptionPane.ERROR_MESSAGE);
            return;
        }
          
        try { bigIntegerN = new BigInteger(inputN); }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, "Parâmetro N com formato incorreto (não é um número)", "Parâmetro incorreto", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        RSAKey key = new RSAKey(bigIntegerKey, bigIntegerN);
        Encrypter decrypter = new Encrypter(key);
        
        decryptedBytes = decrypter.decrypt(bytesReadFromFileDecryption);
        
        System.out.println("Encrypted bytes are ready to rock");
        /* End of RSA encryption section */
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Salvar arquivo decriptado como");
        fileChooser.setFileFilter(new TextFileFilter());
        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.CANCEL_OPTION)
        {
            return;
        }

        File chosenFile = fileChooser.getSelectedFile();

        if(chosenFile.getName().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Nome inválido", "Nome inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String pathToWrite = chosenFile.getAbsolutePath() + ".txt";
        System.out.println("Chosen file to write: " + pathToWrite);
        
        try 
        {
            TextWriter.writeOnFile(pathToWrite, decryptedBytes);
            
            decryptedFilenameField.setText(pathToWrite);
            decryptedFileTextArea.setText(new String(decryptedBytes));
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this, "Erro", "Não foi possível criar o arquivo", JOptionPane.ERROR_MESSAGE);
        }
        
        JOptionPane.showMessageDialog(this, "Decriptação realizada com sucesso!", "Mensagem decriptada", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void generatedPublicKeyToDecryptionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generatedPublicKeyToDecryptionButtonActionPerformed
    {//GEN-HEADEREND:event_generatedPublicKeyToDecryptionButtonActionPerformed
        copyText(RSADecryptKeyTextField, generatedPublicKeyTextArea);
        copyText(NDecryptKeyTextField, generatedNTextArea);
        enableDecryptButtonCheck();
    }//GEN-LAST:event_generatedPublicKeyToDecryptionButtonActionPerformed

    private void generatedPrivateKeyToDecryptionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_generatedPrivateKeyToDecryptionButtonActionPerformed
    {//GEN-HEADEREND:event_generatedPrivateKeyToDecryptionButtonActionPerformed
        copyText(RSADecryptKeyTextField, generatedPrivateKeyTextArea);
        copyText(NDecryptKeyTextField, generatedNTextArea);
        enableDecryptButtonCheck();
    }//GEN-LAST:event_generatedPrivateKeyToDecryptionButtonActionPerformed

    private void useLoadedKeyOnDecryptionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_useLoadedKeyOnDecryptionButtonActionPerformed
    {//GEN-HEADEREND:event_useLoadedKeyOnDecryptionButtonActionPerformed
        copyText(RSADecryptKeyTextField, loadedKeyTextArea);
        copyText(NDecryptKeyTextField, loadedNTextArea);
        enableDecryptButtonCheck();
    }//GEN-LAST:event_useLoadedKeyOnDecryptionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*RSAKey[] keys = KeyFactory.generatePair();
        System.out.println("Public key:\n" + keys[0].toString());
        System.out.println("Private key:\n" + keys[1].toString());*/
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NDecryptKeyTextField;
    private javax.swing.JLabel NKeyDecryptKeyLabel;
    private javax.swing.JTextField NKeyText;
    private javax.swing.JLabel RSADecryptKeyLabel;
    private javax.swing.JTextField RSADecryptKeyTextField;
    private javax.swing.JLabel RSAKeyLabel;
    private javax.swing.JTextField RSAKeyText;
    private javax.swing.JButton chooseFileButton;
    private javax.swing.JButton decryptButton;
    private javax.swing.JButton decryptChooseFileButton;
    private javax.swing.JPanel decryptTab;
    private javax.swing.JTextArea decryptedFileTextArea;
    private javax.swing.JTextField decryptedFilenameField;
    private javax.swing.JLabel decryptionDecryptedFilenameLabel;
    private javax.swing.JLabel decryptionEncryptedFilenameLabel;
    private javax.swing.JLabel decryptionPreviewLabel;
    private javax.swing.JButton deleteKeyButton;
    private javax.swing.JButton encryptButton;
    private javax.swing.JPanel encryptTab;
    private javax.swing.JLabel encryptedFileLabel;
    private javax.swing.JTextField encryptedFilenameDecryptionField;
    private javax.swing.JTextField encryptedFilenameField;
    private javax.swing.JTextArea encryptedTextArea;
    private javax.swing.JButton generateKeysButton;
    private javax.swing.JTextField generatedNTextArea;
    private javax.swing.JTextField generatedPrivateKeyTextArea;
    private javax.swing.JButton generatedPrivateKeyToDecryptionButton;
    private javax.swing.JButton generatedPrivateKeyToEncryptionButton;
    private javax.swing.JTextField generatedPublicKeyTextArea;
    private javax.swing.JButton generatedPublicKeyToDecryptionButton;
    private javax.swing.JButton generatedPublicKeyToEncryptionButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel keyManagementTab;
    private javax.swing.JButton loadKeyButton;
    private javax.swing.JTextArea loadedEncryptedFileTextArea;
    private javax.swing.JTextField loadedKeyTextArea;
    private javax.swing.JTextField loadedNTextArea;
    private javax.swing.JLabel nLabel;
    private javax.swing.JLabel originalFileLabel;
    private javax.swing.JTextArea originalFileTextArea;
    private javax.swing.JTextField originalFilenameField;
    private javax.swing.JLabel previewLabel;
    private javax.swing.JButton savePrivateKeyButton;
    private javax.swing.JButton savePublicKeyButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel transferTab;
    private javax.swing.JButton useLoadedKeyOnDecryptionButton;
    private javax.swing.JButton useLoadedKeyOnEncryptionButton;
    // End of variables declaration//GEN-END:variables
}
